on:
  push:
    tags:
    - releases/edgedb-errors/v*

name: Release edgedb-errors

jobs:
  test_and_publish:
    name: Test and publish
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      # checkout and env setup
      - uses: actions/checkout@v3      
      - uses: dtolnay/rust-toolchain@stable

      # verify that git tag matches cargo version
      - run: |
          set -x
          cargo_version="$(cargo metadata --format-version 1 \
            | jq -r '.packages[] | select(.name=="edgedb-errors") | .version')"
          tag_version="${GITHUB_REF#refs/tags/releases/edgedb-errors/v}"
          test "$cargo_version" = "$tag_version"

      - working-directory: ./edgedb-errors
        run: |
          cargo publish --token=${{ secrets.CARGO_REGISTRY_TOKEN }} --no-verify
